### ISSUE TITLE
django_otp/templates/otp/admin14/login.html: 'future' is not a registered tag library

### ISSUE THREAD

**Issue by narun4sk** [django-otp/django-otp#10]
Lately getting the following error:

```
Invalid template /usr/local/lib/python3.7/site-packages/django_otp/templates/otp/admin14/login.html: 'future' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
... more suggestions ...
```
Any advice please?
```
pip freeze | grep -e Django -e django-otp
Django==2.2.7
django-otp==0.7.3
```

**Comment by psagers** [comment]
For some reason, it's trying to load the template [otp/admin14/login.html](https://github.com/django-otp/django-otp/blob/master/src/django_otp/templates/otp/admin14/login.html), which [makes little sense](https://github.com/django-otp/django-otp/blob/master/src/django_otp/admin.py#L11). If you need a temporary fix, you can override it with your own (perhaps copying [otp/admin19/login.html](https://github.com/django-otp/django-otp/blob/master/src/django_otp/templates/otp/admin19/login.html), which is the most recent one).

The template list should be purged of unsupported versions at this point, but it would still be helpful to know how the version test is going sideways.

**Comment by narun4sk** [comment]
Hmm... The most obscure piece of code that I have in my project which is related to `django_otp` is the following snippet from the `urls.py`:

```
from django.contrib import admin

# Enable Django admin MFA when in the prod mode
if not settings.DEBUG:
    from django_otp.admin import OTPAdminSite
    admin.site.__class__ = OTPAdminSite

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
....
```

Could it be causing that error? The rest of the `django_otp` is pretty standard.

Following your advice, I tried to put a template in `my_project/templates/otp/admin14/login.html`, where I copied the contents from [otp/admin19/login.html](https://github.com/django-otp/django-otp/blob/master/src/django_otp/templates/otp/admin19/login.html), but it seems that it didn't have any positive effect, meaning that it seems it hasn't been picked up.

The error also may be a red herring, as I'm using `django_otp` only as a dependency for [wagtail-2fa](https://github.com/labd/wagtail-2fa), therefore chances are that something in their code does not invoke something in `django_otp`. :man_shrugging:

**Comment by psagers** [comment]
I wasn't familiar with wagtail-2fa; it does sound like there's more to learn here.

**Comment by rdmrocha** [comment]
Ended up here as I'm seeing the exact same thing. In my case, the warning/error is triggered when I run `python manage.py compilescss` (django-sass-processor)

Part of process is to go through all the available templates in the file system and check for scss files to compile. When running, the admin.py from this project can correctly provide the template it needs

@narun4sk I silenced the problem by creating a fake stub in my project under **_your_project_dir/templatetags/future.py_**:



```
from django.template import Library
from django.template.defaulttags import url as _url


register = Library()


@register.tag
def url(*args, **kwargs):
    """
    A stub to get Django Admin scss bootstrap to work since `url` tag
    has been moved from `future` to `defaulttags`.
    """
    return _url(*args, **kwargs)
```

Hope it helps
