### ISSUE TITLE
'Users' object has no attribute 'is_verified'

### ISSUE THREAD

**Issue by OmarSRolo** [django-otp/django-otp#100]
I am using Django 4.0.2 and DRF 3.13.1, I have set the Middleware:

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
 
and I am still having this error, could It be because of the Django version?

**Comment by emmevsombra** [comment]
Have you found the answer? I'm having the same problem

**Comment by joaovitor123jv** [comment]
Also looking for solutions, same issue here only in "production"... "development" version working fine.

**Comment by some1ataplace** [comment]
Seems like a duplicate of #39

**Comment by psagers** [comment]
Duplicate
