### ISSUE TITLE
user.is_verified() constantly returns False, breaking @otp_required decorator

### ISSUE THREAD

**Issue by alstr** [django-otp/django-otp#101]
`user.is_verified()` doesn't seem to be working as expected in Django 4.0.4.

I have a view with the `@otp_required` decorator, which constantly seems to redirect back to my `OTPTokenForm` view, even when that validates correctly.

I replaced the decorator with a custom middleware but the problem remains because the underlying problem seems to be that `user.is_verified()` returns `False` all the time.

Potentially similar issue to #100 but I'm not getting the error described there.

**Comment by alstr** [comment]
This is actually working now and `user.is_verified()` is behaving as expected. The problem was my `OTPTokenForm` view wasn't inheriting from `LoginView`. Maybe improving the documentation for that form class and/or adding a default view would be helpful for people who want to implement a two-stage login (i.e. separate username/password and 2FA views).

**Comment by RyanHope** [comment]
Can you elaborate on your fix a little more. I am trying to otp authentication via restapi and hitting this error.

**Comment by alstr** [comment]
I can't remember exactly, but for some reason not using `LoginView` was causing a problem. I kept the standard `LoginView`, then built a separate OTP verification view for post login, which also inherits from `LoginView` and uses `OTPTokenForm`.
