### ISSUE TITLE
Add ability to pass an html template when rendering email templates

### ISSUE THREAD

**Issue by javialon26** [django-otp/django-otp#103]
It would be really useful to be able to pass an extra template for an HTML message alternative, now only we can send text plain messages. Maybe another configuration `OTP_EMAIL_HTML_BODY_TEMPLATE_PATH` could be the solution.
Thanks

**Comment by some1ataplace** [comment]
#112 Still needs unit tests

**Comment by eschnitzler** [comment]
Made a PR that has tests. Please take a look #125
