### ISSUE TITLE
setting “python_requires” with ">=3.5" is a better way to declare Python compatibility

### ISSUE THREAD

**Issue by PyVCEchecker** [django-otp/django-otp#105]
Hello!

I noticed the dependency of this distribution
```python
    install_requires=[
        'django >= 2.2',
    ],
```
I found that Django>=2.2 requires Python>=3.5,
and there is such a declaration in setup.py
```
classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3 :: Only",
   ...
   ]
```
I guess you want to set python>=3.5. And I think it is a better way to declare Python compatibility by using the keyword argument **python_requires**
* Descriptions in **python_requires** will be reflected in the metadata
* “pip install” can check such metadata on the fly during distribution selection , and prevent from downloading and installing the incompatible package versions. 
* If the user does not specify any version constraint, pip can automatically choose the latest compatible package version for users.

Way to improve:
modify setup() in setup.py, add python_requires keyword argument:
```python
setup(…
     python_requires=">=3.5",
     …)
```
Thanks for your attention.
Best regrads,
PyVCEchecker

**Comment by some1ataplace** [comment]
Yes, you are correct. Updating the setup() function in setup.py to include the python_requires keyword argument with the appropriate version constraint would be a better way to declare Python compatibility for the Django-OTP package.

Using python_requires is a more explicit way to declare the required Python version and ensures that the package will only be installed on a compatible version of Python. This will prevent installation on any unsupported version of Python and also allow pip to automatically choose the latest compatible package version for users who do not specify any version constraint.

The updated code for setup() in setup.py would look like this:

```
setup(
    name='django-otp',
    python_requires='>=3.5',
    install_requires=[
        'django >= 2.2',
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3 :: Only",
        ...
    ],
)
```


By including python_requires` with the appropriate version constraint, users will be informed of the required version of Python during installation and compatibility issues with different Python versions can be avoided.

**Comment by psagers** [comment]
Addressed by recent tooling updates.
