### ISSUE TITLE
RESTAPI authentication flow, user.is_verified problems

### ISSUE THREAD

**Issue by RyanHope** [django-otp/django-otp#107]
I am trying to protect a REST API by requiring OTP but I can't seem to figure out a login/authentication flow that is compat with the OTP middleware. I am using django-knox for per-session token authentication which is working. I can match the token again a device, but I can't seem to get the user.is_verified method to work. Could someone provide a min example of a restapi login with OTP?

**Comment by psagers** [comment]
Honestly, I'm not even sure what it would mean to use 2FA for an API. I can't think of any examples.

Instead, I would suggest having a user-facing interface (i.e. website) that uses whatever authentication mechanisms are appropriate to log in the user and then generate some kind of API key for them to use.

There's a broader pattern we can generalize here: it's valuable to have different authentication contexts for different purposes. The user's primary credentials/hardware tokens/etc. serve as the root. Authenticated users can then receive additional credentials that are appropriate to the circumstances: session cookies, API keys, TLS client certificates, whatever you need. Some APIs will even let you generate multiple API keys with different sets of limited permissions. Ideally, the user's primary credentials should only ever be used to bootstrap them into some other authentication context.

**Comment by RyanHope** [comment]
Why is having a 2FA requirement on an API endpoint so hard to imagine or any different than having it on a normal website view? How does generating a static API key achieve any of the security that 2FA does?

FYI, I am using this as part of a license scheme on some networked software. I wanted to be able to use the OTPRequiredMixin to protect the DH key exchange endpoint. Of course I can just match the otp token against the device in my view manually but that doesn't scale if I decide I want the rest of the views protected with 2fa.

**Comment by psagers** [comment]
Generally speaking, the point of two-factor authentication is to require a user to provide two things to prove their identity: something they know (a password) and something they have (a hardware token, phone, or other physical device). If that's not what you're doing, then you've probably got the wrong tool for the job at hand.

**Comment by RyanHope** [comment]
That is exactly how/why I am using it.

**Comment by psagers** [comment]
Defending against credential sharing is on the other side of the world from this project's goals. You're welcome to use it for anything you see fit, of course, but I have no idea if it will be helpful in this case.

**Comment by RyanHope** [comment]
Here is what I am working with. I added an otp_token field to the AuthTokenSerializer so that I can send the 2FA token with user/pass in the login endpoint. AuthTokenSerializer.validate() calls authenticate() on the user. What am I missing to make things happy?


```
class OTPAuthTokenSerializer(AuthTokenSerializer):
    otp_token = serializers.CharField(
        label=_("OTP"),
        trim_whitespace=False,
        write_only=True
    )

    def validate(self, attrs):
        attrs = super(OTPAuthTokenSerializer, self).validate(attrs)
        if not django_otp.user_has_device(attrs['user']):
            msg = _('No active OTP device.')
            raise serializers.ValidationError(msg, code='authorization')
        otp_device = django_otp.match_token(attrs['user'], attrs.get('otp_token'))
        if otp_device is None:
            msg = _('Invalid OTP.')
            raise serializers.ValidationError(msg, code='authorization')
        attrs['otp_device'] = otp_device
        return attrs
```

```
class LoginView(KnoxLoginView):
    permission_classes = (permissions.AllowAny,)

    def post(self, request, format=None):
        serializer = OTPAuthTokenSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        login(request, user)
        return super(LoginView, self).post(request, format=None)
```

**Comment by RyanHope** [comment]
If I add
`request.session[django_otp.DEVICE_ID_SESSION_KEY] = serializer.validated_data['otp_device'].persistent_id`
before login(), the OTPRequireMixin works but within a post view a call to user.is_verified results in "'User' object has no attribute 'is_verified'"

**Comment by basitiyidir** [comment]
> If I add
> `request.session[django_otp.DEVICE_ID_SESSION_KEY] = serializer.validated_data['otp_device'].persistent_id`
> before login(), the OTPRequireMixin works but within a post view a call to user.is_verified results in "'User' object has no attribute 'is_verified'"

Hi, RyanHope,

How did you fix this problem?
