### ISSUE TITLE
OTP_TOTP_ISSUER cannot be overridden and is stuck on example.com

### ISSUE THREAD

**Issue by rubmz** [django-otp/django-otp#108]
Hi There, and thanks for the wonderful package!
So, I managed setting up a quite functioning MFA with email and TOTP plugins using the wonderful django-two-factor-auth.
Thing is, it seems impossible to override settings parameters, since the django-otp settings are read internally somehow and setting the OTP_TOTP_ISSUER in the projects settings.py won't override it.
I tried numerous other approaches to override that, but the package code is setup such way that TOTPDevice cannot easily be overridden/replaced.
Any workaround?

**Comment by psagers** [comment]
I'm not sure what you're seeing, but it sounds like it's on your end somehow. All settings are meant to be overridden in the usual fashion. OTP_TOTP_ISSUER [defaults](https://github.com/django-otp/django-otp/blob/master/src/django_otp/plugins/otp_totp/models.py#L138) to `None`; it's only set to `"example.com"` in unit tests. There's nothing subtle or sneaky going on here.

**Comment by rubmz** [comment]
nothing sneaky..... right.... and the earth is not flat right??! lol :)

I know it looks like something done wrong on my end. I still suspect our project is using an older version of django... could be... But believe me, more then one person has taken a look at the code and attempts to do the very obvious of setting a variable on the django settings object. There are some ways to go about it - non could break through and actually set the value. It is an odd one. It does look like the code in django-otp is legit, but when I use it under django-two-factor-auth package, which I suspect many do (quite the popular package) it won't get that value. I tried subclassing the otp-totp plugin, trying to set the value under the plugin context and also tried overriding the TOTPDevice.config_url() property implementation, but no good. I gave up and next step is to try and override the qrcode url path in django (ugly workaround...).
Regarding "example.com" - seems that TOTPDevice.config_url() doesn't find any value, creating a qrcode of the url without the issuer. My guess here is that the google authenticator pushes it when it can't find none? Not sure exactly how to test this...

**Comment by rubmz** [comment]
So, yes. My fault. 
Seems that the django-two-factor-auth **replicates the whole QR code piece of code** that's originally in the TOTP QRCODE generator. I totally missed that... and kept trying beating the issuer settings while not even checking that the correct piece of code was running.
