### ISSUE TITLE
django.db.utils.ProgrammingError: relation "django_otp_staticdevice" does not exist

### ISSUE THREAD

**Issue by mbml84** [django-otp/django-otp#109]
I got this problem when I tried to use static device. 

`django.db.utils.ProgrammingError: relation "django_otp_staticdevice" does not exist`

I solved it locally by running these commands :

`python manage.py makemigrations django_otp`
`python manage.py migrate`

..but it's not an ideal solution for production environment.

**Comment by mbml84** [comment]
Yes I needed to run `makemigrations django_otp` before running `migrate`. I can't see any migartion files created but I know that without running makemigrations, I can't use static device.

**Comment by mbml84** [comment]
I don't know where the files are stored but in my terminal I see that migrations are created. Sorry If I wasn't clear

**Comment by psagers** [comment]
If you can put together repro steps in a clean environment, I'll have a look.

Thanks

**Comment by psagers** [comment]
Did you add `'django_otp.plugins.otp_static'` to your `INSTALLED_APPS`?

https://django-otp-official.readthedocs.io/en/stable/overview.html#installation

The `django_otp` app itself has no concrete models and should have no migrations. The fact that you can create them at all is odd and possibly a bug, but I suspect it's downstream of a configuration issue.

**Comment by mbml84** [comment]
No I forgot to add it. It solved my problem. Thank you!
