### ISSUE TITLE
No option to disable logging of static tokens

### ISSUE THREAD

**Issue by sarahfmurray** [django-otp/django-otp#11]
When using the 'addstatictoken' management command, the text of the token is logged using self.stdout.write. Is there a way to optionally disable this logging if I don't want it?

**Comment by moggers87** [comment]
stdout can be redirected to /dev/null like this:

```
$ ./manage.py addstatictoken username > /dev/null
```

**Comment by sarahfmurray** [comment]
Ahh, OK thanks. I didn't think of doing that.
