### ISSUE TITLE
Customizing the user label in config url for OTP devices

### ISSUE THREAD

**Issue by dsego** [django-otp/django-otp#146]
TOTPDevice `config_url` method allows for customizing the issuer via the `OTP_TOTP_ISSUER` setting. 
The label however is hardcoded to the username prop via `label = str(self.user.get_username())`.  

In our application the username is filled with random guid strings and we have an extra email field.  This was set up in this way long before I joined. I wouldn't want to override the `get_username` because I don't understand the effects on other parts of the app.

Would it be possible to override the label somehow?

1) Eg method on the user model
```python
class CustomUser(AbstractUser):
    @property
    def otp_totp_label():
       return self.email
       
class TOTPDevice(TimestampMixin, ThrottlingMixin, Device):
       ...
       @property
       def config_url(self):
            if hasattr(user, 'otp_totp_label'):
                 label = str(self.user.otp_totp_label)
            else:
                 label = str(self.user.get_username())
```

2) Or a setting like `OTP_TOTP_LABEL_FIELD="email"`

```python
       @property
       def config_url(self):
            if settings.OTP_TOTP_LABEL_FIELD:
                 label = str(gettattr(self.user, OTP_TOTP_LABEL_FIELD))
            else:
                 label = str(self.user.get_username())

```

**Comment by psagers** [comment]
Either of those could work. The second one is a little less flexible, but more consistent with similar features (and easy to document).

Could  you also just define a proxy model and override `config_url` altogether?

**Comment by dsego** [comment]
> Could you also just define a proxy model and override config_url altogether?

That was my first idea, would I need to make a new migration and tables for it though? 

> If you’re using it in your own views, you can always just copy the code and customize it to your liking. If you’re using it in the admin UI, it might be easier to override it at the ModelAdmin level rather than in the model.

Good point. I was using the django admin to test it out, but you are correct that I can write a small helper to generate the config URL. 
```
def generate_otp_device_url(device):
    params = {
        'secret': b32encode(otp_device.bin_key),
        'algorithm': 'SHA1',
        'digits': otp_device.digits,
        'period': otp_device.step,
    }
    urlencoded_params = urlencode(params)
    label = device.user.email
    issuer = 'foo'
    issuer = issuer.replace(':', '')
    label = '{}:{}'.format(issuer, label)
    urlencoded_params += '&issuer={}'.format(quote(issuer))
    url = 'otpauth://totp/{}?{}'.format(quote(label), urlencoded_params)
    return url
```

This actually solves the problem for my use case. Let me know if it makes sense to leave the issue open or we can close it.
