### ISSUE TITLE
Feature request: Override template paths for otp_email generate_challenge()

### ISSUE THREAD

**Issue by swayll** [django-otp/django-otp#159]
Please make it possible to specify other templates for email generation using `generate_challenge()`.
I use different templates for different tasks, but in the plugin settings (`OTP_EMAIL_BODY_TEMPLATE_PATH`, `OTP_EMAIL_BODY_HTML_TEMPLATE_PATH`, ...) I can specify only one template, which is not convenient to format for different tasks.

Thank you!

**Comment by psagers** [comment]
Pull requests welcome.

Also, a regular friendly reminder that the device implementations built into django-otp are all small, simple, and [un-licensed](https://github.com/django-otp/django-otp/blob/master/LICENSE). They serve as demos as much as working implementations. All developers are welcome, indeed encouraged, to use them as inspiration or starting points for their own private or public device plugins that serve their particular purposes.
