### ISSUE TITLE
ISE during verification in LoginView

### ISSUE THREAD

**Issue by vsemionov** [django-otp/django-otp#2]
Hi,

Many thanks for this wonderful project!

I found the following issue with `LoginView`. When verifying a user that is already authenticated, the `LoginView` uses `OTPTokenForm`. Unlike `OTPAuthentication`, `OTPTokenForm` does not call `authenticate()` when validating the form data. The `authenticate()` function populates the user with a `backend` attribute. Therefore, during verification of authenticated users, the user object is left without this attribute. If the token is valid, the user is logged in by calling `login()`. This function expects the `backend` attribute. If it does not exist, it uses the backend, configured in settings. But if more than one backend is configured, it throws an error. Therefore, verifying authenticated users, with multiple configured auth backends, is not supported out of the box. Having more than one backend is not uncommon or exotic. In my case, I have two backends - one from `django-axes` and one from `django-allauth`.

`django-otp` version: 0.7.1

The following stacktrace is produced:
```
Internal Server Error: /backend/login/
Traceback (most recent call last):
........
  File "/Users/victor/anaconda3/envs/myapp/lib/python3.7/site-packages/django/contrib/auth/views.py", line 90, in form_valid
    auth_login(self.request, form.get_user())
  File "/Users/victor/anaconda3/envs/myapp/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 118, in login
    'You have multiple authentication backends configured and '
ValueError: You have multiple authentication backends configured and therefore must provide the `backend` argument or set the `backend` attribute on the user.
```

I've worked around this problem with the following subclass:
```python
from django_otp.views import LoginView
from django.contrib.auth import BACKEND_SESSION_KEY

class CustomLoginView(LoginView):
    def form_valid(self, form):
        user = form.get_user()
        if not hasattr(user, 'backend'):
            user.backend = self.request.session[BACKEND_SESSION_KEY]
        return super().form_valid(form)
```

I hope this helps. Please let me know if you need more information, or if you'd like a pull request.

Best regards,
Victor

**Comment by psagers** [comment]
Good catch. I think this is the right fix and I added some test cases as well. Version 0.7.2.
