### ISSUE TITLE
Idea: mark static device as unconfirmed when last token is used

### ISSUE THREAD

**Issue by arjan-s** [django-otp/django-otp#20]
It would be nice (from a user's perspective) if a static device is marked unconfirmed when the last token is used. This helps the user to decide it's time to generate new tokens.

**Comment by some1ataplace** [comment]
To mark a static device as unconfirmed when the last token is used, you can add a signal to the django_otp.plugins.otp_static.models.StaticDevice model that listens for a token_verified signal.

Here's an example implementation of the signal receiver:

```
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.signals import token_verified


def mark_device_unconfirmed(sender, user, device, **kwargs):
    last_token = device.tokens.last()
    if last_token is not None and last_token.verify():
        device.confirmed = False
        device.save()
        

token_verified.connect(mark_device_unconfirmed, sender=StaticDevice)
```


The above code adds a signal receiver mark_device_unconfirmed that listens for token_verified signal from the StaticDevice. It checks if the last token on the device is not null and is verified. If it is, then it sets the confirmed attribute of the device to False and saves the device object.

This will mark the device as unconfirmed after the last token has been used and verified, indicating to the user that it's time to generate new tokens.

**Comment by psagers** [comment]
> from django_otp.signals import token_verified

No such signal (or module) exists. A `pre_delete` or `post_delete` handler on the `StaticToken` would do the trick just as well.

The `confirmed` flag exists for the convenience of implementers to use as they see fit. The core project does not use it to communicate state.
