### ISSUE TITLE
Version 0.8.0 on pypi breaks build

### ISSUE THREAD

**Issue by normoes** [django-otp/django-otp#24]
There is a new version (`0.8.0`) on pypi. 
This version is not mentioned in the change log on read the docs, nor is it published as a release here on github.

I use `django-two-factor-auth==1.10.0` (with Django `2.2.10` and python `3.7.6`), which used to install `django-otp==0.7.5` As of yesterday, since there are no further constraints, it installed `django-otp==0.8.0`.

And since today/yesterday my builds break, because:
```
File "/home/service/.local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 801, in get_default
     return self._get_default()
   File "/home/service/.local/lib/python3.7/site-packages/two_factor/models.py", line 57, in random_hex_str
     return random_hex().decode('utf-8')
 AttributeError: 'str' object has no attribute 'decode'
```

After forcing `django-otp==0.7.5` it works again.

**Comment by normoes** [comment]
Looks like python2 syntax run with python3.

**Comment by claudep** [comment]
This is fixed in django-two-factor-auth master (https://github.com/Bouke/django-two-factor-auth/commit/0fc4a54a14bc9e42d48c0e99c01d5ec31a120685), you should pin django-otp to 0.7.5 until two-factor has a new release.

**Comment by normoes** [comment]
Perfect. To be honest,my main concern was that this (`0.8.0`) is no official version and was hacked or something ;)

Thanks for calming me.
