### ISSUE TITLE
Token field no longer rendered on login for anonymous users

### ISSUE THREAD

**Issue by vsemionov** [django-otp/django-otp#26]
After upgrading to `0.8.0` (from `0.7.5`), the admin login form no longer shows the token field if the user is currently anonymous. It is no longer possible to authenticate and verify in a single form post.

The problem is in the new 1.11 template. The rendering of the `otp_token` field has now been moved into the `{% if form.get_user %}` check. Please see the below diff snippet:
```diff
   </div>
   {% if form.get_user %}
   <div class="form-row">
-      <label for="id_otp_device">{% trans 'OTP Device:' %}</label> {{ form.otp_device }}
+    {{ form.otp_device.errors }}
+    <label for="id_otp_device">{% trans 'OTP Device:' %}</label> {{ form.otp_device }}
   </div>
-  {% endif %}
   <div class="form-row">
-    {% if not form.this_is_the_login_form.errors %}{{ form.otp_token.errors }}{% endif %}
+    {{ form.otp_token.errors }}
     <label for="id_otp_token" class="required">{% trans 'OTP Token:' %}</label> {{ form.otp_token }}
   </div>
+  {% endif %}
   {% url 'admin_password_reset' as password_reset_url %}
   {% if password_reset_url %}
   <div class="password-reset-link">
```
Note that `{% endif %}` has been moved a few lines down. I believe only this slight change should be reverted.

Cheers and thanks for the great project!

**Comment by psagers** [comment]
cc @claudep

**Comment by claudep** [comment]
I'll handle this ASAP.

**Comment by claudep** [comment]
Sorry, I had not this scenario in my mind, I was sure that the token was always asked in a second stage of the authentication.

**Comment by vsemionov** [comment]
Thank you both for the super quick responses!

**Comment by psagers** [comment]
Thanks, Claude. Frankly, if I were doing it today, I might not implement this kind of preemptive verification; it's kind of a hack to fit into the admin login flow, which we have little control over. Still, that's the way it's always been, so might as well maintain compatibility.
