### ISSUE TITLE
Feature request: Generic SideChannelDevice for token generation and management

### ISSUE THREAD

**Issue by arjan-s** [django-otp/django-otp#32]
As pitched by @psagers in https://github.com/django-otp/django-otp/pull/4, this is a request for a generic abstract SideChannelDevice. This should implement the token generation, validation and expiry while leaving delivery to the concrete devices.

**Comment by arjan-s** [comment]
Btw, I've started an initial implementation [here](https://github.com/arjan-s/django-otp/tree/sidechanneldevice).

**Comment by rjmackay** [comment]
Sorry to come to this late, I'm just reading through this library and assessing it for my own uses. 
@arjan-s I'm curious why SideChannelDevice doesn't use TOTP to generate tokens? (similar to the TwilioSMSDevice in django-otp-twilio)

Is this just a reflection of how it was implemented in the EmailDevice prior to being moved to it's own class? Or is there more to it than that?

**Comment by psagers** [comment]
TwilioSMSDevice should be migrated to SideChannelDevice. Using TOTP was expedient when I was originally throwing these things together, but the new SideChannelDevice is definitely superior.

**Comment by rjmackay** [comment]
@psagers thanks for the fast response! 
That makes sense. I guess I'm still just a little unsure if there are advantages/disadvantages to just storing the `key` and generating the token as in TOTP vs storing the actual `token` as in SideChannelDevice?

**Comment by psagers** [comment]
If you're delivering a token, there's going to be some kind of interaction to kick off the process, so you ignore one of the main benefits of TOTP, which is avoiding a back-and-forth. At the same time, if you have a 30-second token, it will expire anywhere from 0 to 30 seconds after you request it (or rather 30 to 60 or some such variation). By generating a token and storing the time, you know it will expire exactly X seconds from the moment it was requested.

HOTP/TOTP is an admirable solution to the problem of manufacturing OTP devices that don't require or support any kind of challenge-response process. It's a comically convoluted solution for verifying access to a communication channel. It was kind of a classic case on my part of getting distracted by the shininess of the solution space and losing sight of the actual problem.

**Comment by arjan-s** [comment]
@rjmackay I completely agree with @psagers. I would just like to add one remark: it's usually best to choose an implementation that's least complex to accomplish a certain task. While TOTP is good at what it's meant to do, it adds unnecessary complexity to the simple task of generating a random token and expiring it.
