### ISSUE TITLE
Making requests too fast removes verification for user and sends him to verification page

### ISSUE THREAD

**Issue by Jane-Terziev** [django-otp/django-otp#37]
Hello, I've implemented the 2fa to the projects fairly easy. I'm using Django 2.2.6 and django-otp 0.7.3 and everything works fine.

I have a monolith web application with server side rendering using Django Templates and Ajax calls for pagination on tables. The backend returns the new table as html and i replace the current table with the new one.

The problem is when i click on the pagination too fast and spam requests, the backend removes the verification from the user and returns a 302 redirect to the verification page. The user remains authenticated, but not verified.

I've looked through the source code and haven't found any setting that removes the verification if requests are coming too fast or a limit on how many request a user can make per second.

I didn't find any resources about this on stackoverflow, any help would be appreciated.

Thank you for the package.

**Comment by psagers** [comment]
I believe there's only [one place](https://github.com/django-otp/django-otp/blob/2b929003a3547df44ce77e38977373d427c65a13/src/django_otp/middleware.py#L49) where we might un-verify a session, and it's only to defend against invalid state. Certainly I can't think of any way this would be expected behavior. It could be a canary indicating some deeper issues you're having with session management.

**Comment by some1ataplace** [comment]
If clicking on the pagination too fast is causing the backend to remove verification from the user, it's likely that the backend is receiving too many requests too quickly and interpreting them as potentially malicious activity. One potential solution would be to implement rate limiting on the backend to restrict the number of requests that can be made in a given time period.

Django has a library called django_ratelimit that can be used to implement rate limiting. With django_ratelimit, you can decorate your view functions with a rate limiting decorator, specifying the maximum number of requests that can be made in a given time period. If the user exceeds the limit, the view function will return an HTTP 429 Too Many Requests status.

Another potential solution would be to implement client-side rate limiting using JavaScript. You could disable the pagination buttons for a brief period of time after a button is clicked, to prevent the user from making too many requests too quickly. This would give the backend time to process the request before the user sends any more requests.
