### ISSUE TITLE
Cannot see the admin login form field

### ISSUE THREAD

**Issue by 9mido** [django-otp/django-otp#42]
@claudep  @psagers 

Tried following this video tutorial exactly and I am unable to see the OTP form fields on the admin login page. It just shows the username and password fields only.

https://www.youtube.com/watch?v=TGvK5z9R8Ik

Code from the video is in the comments. Try sorting by new in youtube if the code comment does not show up at first.

As an admin user, I can login without a token even though in the admin backend OTP devices are enabled for that user.

When overriding the login.html template in my project/templates/admin/login.html and pasting in this entire code:
https://github.com/django-otp/django-otp/blob/master/src/django_otp/templates/otp/admin111/login.html

It only shows the label text "OTP Token" and the input tag itself is missing as if {{ form.otp_token }} and {{ form.otp_device }} does not work. 

Deleting the  {% if form.get_user %} if statement shows the "OTP Device" label but not the input tag.

Seems like a lot more steps to override the login.html template compared to the steps the video. Did something change for the worst? 

Might be related to #26 which was closed.

**Comment by 9mido** [comment]
Update:

I added this to urls.py:

from django_otp.admin import OTPAdminSite
admin.site._class_ = OTPAdminSite

Now the form fields show up in the admin login page. Am I missing anything? If not, feel free to close this issue.

**Comment by psagers** [comment]
This video was created by a third party and is not connected to the project. Official documentation is at https://django-otp-official.readthedocs.io/.
