### ISSUE TITLE
Existing Admin Users Cannot Enable 2FA

### ISSUE THREAD

**Issue by 9mido** [django-otp/django-otp#44]
If you already have existing admin users and then install the django-otp package, those already existing admin users cannot enable 2FA.

There should be some way to detect this or also have the existing admins be able to enable 2FA.

Otherwise the only workaround is to migrate the database first, set up the existing admins, then enable admin.site.__class__ = OTPAdminSite to urls.py. Perhaps you could close this issue just add this to the docs to make it clear for users to migrate to the database first then setup the existing admins then enable that 1 line of code. 

If using docker, be sure to comment out admin.site.__class__ = OTPAdminSite in urls.py and any related OTP custom forms.py code if you have any. Then run docker container restart <container_id> to be able to login as an admin user to then setup OTP tokens for that admin user.

**Comment by adamyala** [comment]
This issue seems to still be relevant, so I wanted to share my workaround. Inspired by https://github.com/django-otp/django-otp/issues/64

We have staff users pre-existing in our system. I used the below script to create a device for the staff user, then print out a token so they can sign in. Once they're logged into the admin they can find their created device and set it up on their actual physical device.

```python
from django_otp.plugins.otp_totp.models import TOTPDevice
from django_otp.oath import totp

from users.models import User


user = User.objects.get(id=1)
device = TOTPDevice.objects.create(user=user)
token = totp(device.bin_key)

print('user', user)
print('6 digit token', token)
```

**Comment by psagers** [comment]
This looks a lot like [addstatictoken](https://django-otp-official.readthedocs.io/en/stable/overview.html#addstatictoken).

**Comment by adamyala** [comment]
@psagers That's exactly what I wanted! I missed that in the docs. TYVM!

**Comment by some1ataplace** [comment]
Admin.py file in your own app

Modify the UserAdmin class from django-otp to allow admins to enable 2FA for existing users:

```
from django.contrib import admin
from django_otp.admin import OTPAdminSite
from django_otp.plugins.otp_totp.models import TOTPDevice
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth.models import User

class MyOTPAdminSite(OTPAdminSite):
    pass

admin_site = MyOTPAdminSite(name='otpadmin')

@admin_site.register(TOTPDevice)
class TOTPDeviceAdmin(admin.ModelAdmin):
    pass

class MyUserAdmin(UserAdmin):
    def has_change_permission(self, request, obj=None):
        if obj is not None and obj.id == request.user.id:
            return True
        return super().has_change_permission(request, obj)

    def get_fieldsets(self, request, obj=None):
        fieldsets = super().get_fieldsets(request, obj=obj)
        if request.user.is_superuser:
            fieldsets += (('OTP Settings', {'fields': ('otp_enabled',)}),)
        return fieldsets

    def save_model(self, request, obj, form, change):
        is_new = obj._state.adding
        
        if is_new and form.cleaned_data.get('otp_enabled', False):
            device = TOTPDevice.objects.create(
                user=obj,
                name='Primary device',
            )
        
        super().save_model(request, obj, form, change)

admin_site.register(User, MyUserAdmin)

admin.site.disable_action('delete_selected')
```

This modified UserAdmin class adds a new fieldset to the change form for superusers that includes an OTP enabled checkbox. When a superuser enables OTP authentication for a user, the save_model method creates a new TOTPDevice object for that user to use for 2FA. The has_change_permission method grants the user permission to update their own 2FA status, but only grants superusers permission to update other users' statuses.

To enable this modified admin site, register it under a new URL in your root urls.py file:

```
from django.conf.urls import url
from my_otp_admin import admin_site

urlpatterns = [
    url(r'^admin-otp/', admin_site.urls),
    url(r'^admin/', admin.site.urls),
]
```


With this setup, admins can now enable 2FA for existing users and manage their OTP devices through the new admin interface at /admin-otp/. 


***


To detect if an existing admin user does not have 2FA enabled

```
from django.contrib.auth.models import User
from django_otp.models import Device


def check_admin_otp_enabled(user):
    """
    Check if an admin user has OTP devices enabled.
    """
    try:
        admin_device = Device.objects.get(user=user)
    except Device.DoesNotExist:
        # If the admin user has no devices enabled, their 2FA is not enabled
        return False
    else:
        return True

admin_user = User.objects.get(username='some_admin_username')
if not check_admin_otp_enabled(admin_user):
    # Admin user does not have 2FA enabled - take appropriate action

# Find all admin users who don't have 2FA enabled and enable it for them
admin_users = User.objects.filter(is_staff=True, is_superuser=True)
for admin_user in admin_users:
    if not check_admin_otp_enabled(admin_user):
        # Enable TOTP device for the admin user
        TOTPDevice.objects.create(user=admin_user, name='Default')
        print(f'2FA enabled for admin user: {admin_user.username}')
```
