### ISSUE TITLE
Django-allauth Staff Able To Login To Admin Without OTP Token From The Frontend

### ISSUE THREAD

**Issue by 9mido** [django-otp/django-otp#45]
Using django-allauth, a staff admin user is able to login normally from the frontend of my site. Then when that staff user tries to access the /admin/ login page, they are able to bypass the login form which asks for the OTP token, and are logged into admin automatically. 

This is also the case without this package installed. But it would be nice to have an option like a setting to include a way to require admin staff users who are logged into the frontend to be forced to enter the OTP token on the /admin/ login backend page every time they try to access the /admin/ URL. 

An idea would be to make it so staff must use the OTP token to log in no matter which login view they use. Or you could block access to the frontend for staff users.

**Comment by psagers** [comment]
I don't know anything about django-allauth, but generally speaking, you're responsible for making sure that any view you hook into your URLs is enforcing whatever authentication or authorization policies you need. This may mean decorating individual views, subclassing admin sites, or even writing a tiny piece of middleware that enforces some policy across all views.

Is there anything here that is hard to solve outside of django-otp? So far it just sounds like routine integration.

**Comment by 9mido** [comment]
I seemed to have find a good enough solution:

https://stackoverflow.com/a/57357586/13955916

If anyone has any issues with this, like a security issue, please let me know.
