### ISSUE TITLE
Incorrect number of digits generated

### ISSUE THREAD

**Issue by subodh-malgonde** [django-otp/django-otp#47]
the `hotp` function sometimes returns incorrect number of digits. Below are some examples where this happens. I set the `digits` argument to **4**, but it returns a token with 3 digits.

```
>>> hotp(b'\x07\xd4\x9ey\xeeh\x87\xc3I\xac\xfa\xa3VR9\xe1\xf1\x96\x02)', 54, digits=4)
243

>>> hotp(b'\x07\xd4\x9ey\xeeh\x87\xc3I\xac\xfa\xa3VR9\xe1\xf1\x96\x02)', 56, digits=4)
676

>>> hotp(b'\x07\xd4\x9ey\xeeh\x87\xc3I\xac\xfa\xa3VR9\xe1\xf1\x96\x02)', 71, digits=4)
154

>>> hotp(b'\x07\xd4\x9ey\xeeh\x87\xc3I\xac\xfa\xa3VR9\xe1\xf1\x96\x02)', 86, digits=4)
738
```

Let me know how to fix this.

**Comment by moggers87** [comment]
Python integers don't display a leading 0, for example: 

```
>>> print(int("0738"))
738
```

However, you can tell Python you want leading 0s when casting to string:

```
>>> print("{:04d}".format(738))
0738
```
