### ISSUE TITLE
Enable extra widget attributes on login form fields

### ISSUE THREAD

**Issue by truthdoug** [django-otp/django-otp#62]
I'd like to add `data-lpignore="true"` to the `otp_token` field on the login form to indicate that LastPass shouldn't save or try to pre-populate this field. 

Is there a way currently that I can accomplish this? 

Otherwise, it'd be nice to have something where we can add extra attributes to the form field's widget.

**Comment by psagers** [comment]
The forms are all just Form classes. You can subclass them and replace the fields or override `__init__` and modify them. E.g. `self.fields['otp_token'].widget.attrs['data-lpignore'] = 'true'` maybe. Normal Django stuff, unless I'm overlooking something.

**Comment by truthdoug** [comment]
That makes sense, I tried something quick:

    class ForgetfulOTPAdminSite(OTPAdminSite):
    """Doesn't offer autocomplete for OTP token and tells LastPass not to remember the token."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.login_form.base_fields['otp_token'].widget.attrs['data-lpignore'] = 'true'
        self.login_form.base_fields['otp_token'].widget.attrs['autocomplete'] = 'off'

and in urls.py, I added: `admin.site = ForgetfulOTPAdminSite()`

I got what I expected on the login form but when I logged in, I had no permissions on any objects.

**Comment by truthdoug** [comment]
I got it working. 

Rather than defining `admin.site` in urls.py, I instead created a custom AdminConfig class as described in [Django's docs about overriding the default admin site](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#overriding-the-default-admin-site).

    class ForgetfulAdminConfig(AdminConfig):
        default_site = 'myproject.myapp.ForgetfulOTPAdminSite'

and then put that into `INSTALLED_APPS` instead of `django.contrib.admin`:

    -    'django.contrib.admin',
    +    'myproject.myapp.ForgetfulAdminConfig',
