### ISSUE TITLE
TOTP token comparison might be susceptible to timing attacks

### ISSUE THREAD

**Issue by 54sledgehammer45** [django-otp/django-otp#66]
https://github.com/django-otp/django-otp/blob/a4f947ce8d1e4f78241cffb589b130196f7b77af/src/django_otp/oath.py#L189

In order for it to be susceptible one would require `OTP_TOTP_THROTTLE_FACTOR = 0 `. That in itself is already a bad value, but constant-time comparisons should however be used regardless.

**Comment by psagers** [comment]
That's why it's comparing tokens as ints rather than strings.
