### ISSUE TITLE
Provide time at which throttling lock expires

### ISSUE THREAD

**Issue by Feuermurmel** [django-otp/django-otp#71]
When a Device is "locked" due to throttling, `ThrottlingMixin.verify_is_allowed()` returns `(False, info_dict)`. `info_dict` contains the number of failed attempts but provides no information about how long or until when the device is locked due to throttling. I assume that in may cases this information would be helpful for the user and I think it could easily be provided by `verify_is_allowed()`.

I suggest that a new key is added to `info_dict`, e.g. `{..., 'locked_until': datetime.datetime(…)}` or something similar. What do you think?

**Comment by psagers** [comment]
Sounds reasonable to me.

**Comment by psagers** [comment]
Version 1.0.3.
