### ISSUE TITLE
Issue with migrations

### ISSUE THREAD

**Issue by lijoev** [django-otp/django-otp#72]
I have installed django otp for my project and I have migrated all the changes to my database and when I tried to create migration files for my apps using the below command

`**python manage.py makemigrations**`

django-otp creates some migration files which deletes EmailDevice, StaticDevice, StaticToken, TotpDevice  tables of django-otp. Please help me to resolve this issue.
I am attaching those 3 migration files which is created in effect of this command. 

![Screenshot 2021-03-18 at 2 57 29 PM](https://user-images.githubusercontent.com/19813885/111603367-48ed0a00-87fa-11eb-86f9-fa63e3e24c20.png)

![Screenshot 2021-03-18 at 2 58 08 PM](https://user-images.githubusercontent.com/19813885/111603434-5c987080-87fa-11eb-8733-6caee3d5a279.png)
![Screenshot 2021-03-18 at 2 58 33 PM](https://user-images.githubusercontent.com/19813885/111603495-6c17b980-87fa-11eb-9380-78b87ecc6fe4.png)

I am using python 3.9 and django 3.1.7
Please help me to resolve this issue.

**Comment by psagers** [comment]
I quickly tried to reproduce this using the given versions with the `test_project` in the repo and didn't see it. Have you tried to create a minimal sample project that demonstrates this?

**Comment by lijoev** [comment]
Thanks @psagers  I could resolve this. It was an issue with renaming the app label in my admin.py
