### ISSUE TITLE
Possible circumvention of otp, no logging of potential abuse

### ISSUE THREAD

**Issue by stitch** [django-otp/django-otp#75]
Hi!

First off: Thanks for django_otp!

Why this request:
It seems there is a way around django_otp with a 6 digit token. An attacker can just try the same codes (up to 3 every 30 seconds it seems) for months on end. Throttling will not stop this, i've tried this for a few minutes. It seems that given enough time (months), the attacker is able to log in as the OTP will change every 30 seconds :). So you're not brute forcing, but the OTP is doing that for you.

This could be detected if:
1) wrongly entered codes (the ValidationErrors) are also logged, so operation can notice suspicious behavior. For example including the username or something that indicates which users credentials might have leaked. Signals might also work.
2) throttling is very useful for quicker attacks, but after tons of wrong codes there should be a block on logging in (that should be a django_two_factor_auth thing).

Logins are already monitored but that might not be enough in busy applications.

Does this make sense? Did i overlook something for these claims?

**Comment by psagers** [comment]
I think this can probably be reformulated a bit more simply. Assuming the codes are effectively random and you have k guesses per code, then after n codes, the chances of having guessed correctly are `1 - (((10^6 - k) / 10^6) ^ n)`. With 3 guesses every 30 seconds for a year, that gets up to about 95%.

Placing a limit on invalid codes sounds attractive, but remember the flip side: an attacker could take advantage of that to deliberately max out a user's account, creating a denial of service vulnerability. This is why rate-limiting is typically tied to requesting IPs (and why distributed DOS attacks are so hard to mitigate without collateral damage). Suppressing suspicious login activity without creating DOS vulnerabilities is a Hard Problem.

Using a signal to give projects enough information to implement their own rate-limiting policies sounds entirely reasonable. Logging could be tied into this by default or left to the projects as well.

**Comment by stitch** [comment]
Thanks for the detailed and quick response.

I assume this gets harder because the otp is not always behind credentials, which adds complexity. In case when the otp asked after a username/password an attacker already has obtained these credentials. Logging erroneous otp attempts would make this more evident, unless the attacker wins the lottery :) -in short: That signal would be very valuable!

**Comment by psagers** [comment]
Pull requests welcome.

**Comment by some1ataplace** [comment]
First, let's define a LoginAttempt model that will keep track of failed login attempts for each user. This model will have a foreign key to the User model, as well as fields for the attempted OTP code, the timestamp of the attempt, and a boolean field indicating whether the attempt was successful or not:

```
from django.db import models
from django.contrib.auth.models import User

class LoginAttempt(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    otp_code = models.CharField(max_length=6)
    attempted_at = models.DateTimeField(auto_now_add=True)
    successful = models.BooleanField(default=False)
```

Next, let's modify the OTPMiddleware class to log login attempts to the database, and to check for suspicious login activity. We'll add a check to verify that a user has not had too many failed login attempts in a given timeframe. Here's the modified class:

```
from django.utils import timezone
from django_otp.middleware import OTPMiddleware
from django_otp.models import Device
from .models import LoginAttempt

class CustomOTPMiddleware(OTPMiddleware):
    def _verify_user(self, request, user):
        """
        Verify user using Django-OTP and log login attempts to the database.
        """
        verified = False

        # Call parent method to get OTP device
        device = super()._verify_user(request, user)

        # If device is None, authentication has failed
        if not device:
            # Log failed login attempt to database
            login_attempt = LoginAttempt(user=user, otp_code='', successful=False)
            login_attempt.save()
            return False

        # Check if user has had too many failed login attempts in the last X minutes
        num_failed_attempts = LoginAttempt.objects.filter(
            user=user,
            successful=False,
            attempted_at__gte=timezone.now() - timezone.timedelta(minutes=5)
        ).count()

        if num_failed_attempts >= 5:
            # Log suspicious activity to database
            login_attempt = LoginAttempt(user=user, otp_code='', successful=False)
            login_attempt.save()
            return False

        # Log successful login attempt to database
        login_attempt = LoginAttempt(user=user, otp_code=device.token, successful=True)
        login_attempt.save()
        return True

    def process_request(self, request):
        """
        Override process_request to add device encoding to the session.
        """
        # Call parent method to encode device in session
        super().process_request(request)

        # If user is authenticated and OTP device is verified, set session variable
        if request.user.is_authenticated and getattr(request.user, 'otp_device', None) is not None and request.user.otp_device.confirmed:
            request.session['otp_device'] = request.user.otp_device.persistent_id

        return None
```

In this implementation, we have added a LoginAttempt model to keep track of failed login attempts for each user, as well as a check for suspicious activity after a certain number of failed attempts. We also log successful login attempts to the database.

Furthermore, we have overridden the _verify_user method in OTPMiddleware to include the logging of login attempts to the database. Finally, we added a check in process_request to set the otp_device session variable if the user is authenticated and their OTP device is verified.

**Comment by hottwaj** [comment]
Hi there, thanks for this issue thread and package.

Do you think that django-otp would already work with, or could be made to rely on, another package that avoids such brute force attacks?

For example, Django Axes already provides means for locking out users that have had two many failed password attempts:
https://pypi.org/project/django-axes/
