### ISSUE TITLE
otp_totp plugin username filed as UUID

### ISSUE THREAD

**Issue by callefoss** [django-otp/django-otp#77]
Hi,
I have my username field as type UUID. 
Seems that method config_url in otp_totp/models.py

`label = self.user.get_username()`

...label ends up being a UUID which does not work for quote method in urllib since it is expecting a string.

Any ideas on how to fix this? Can label be casted to a string here or any other ways of having self.user.getusername() end up being a string somewhere else in my code?

//Thanks

**Comment by psagers** [comment]
If your username is not human-readable, then you may not want to be using the built-in `config_url` anyway. My first suggestion is that you just copy the code and generate the configuration parameters that make the most sense for your situation (using the email address or whatever else you have for the label).

As far as I can recall, calling `config_url` is entirely optional, so I'm assuming you're not just completely blocked by this exception. If it is important to work around this inside `config_url`, I'm sure we can do something. Pull requests welcome.

**Comment by psagers** [comment]
Minimal fix in 1.0.5.
