### ISSUE TITLE
Make QR code white on dark background

### ISSUE THREAD

**Issue by 9mido** [django-otp/django-otp#78]
The django admin interface seems to respect your operating system's theme of either light mode or dark mode. Currently, the QR code image is impossible to scan if on a dark mode background.

**Comment by micwoj92** [comment]
Did you update to latest version? This should be resolved. Background is set to white.
https://github.com/django-otp/django-otp/issues/76

**Comment by 9mido** [comment]
Oh I did not thank you for pointing that out I will close this then.
