### ISSUE TITLE
Update documentation on how to replace the default admin site with OTPAdminSite

### ISSUE THREAD

**Issue by jaap3** [django-otp/django-otp#90]
Django has had an "official" way to replace the default admin site, documented here: https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#overriding-the-default-admin-site (Introduced in Django 2.1)

Basically it boils down to adding the following to a project:

```
from django.contrib.admin.apps import AdminConfig as DefaultAdminConfig


class AdminConfig(DefaultAdminConfig):
    default_site = 'django_otp.admin.OTPAdminSite'
```

and then replacing ''django.contrib.admin'` in `INSTALLED_APPS` with the path to this new module.

django-otp could even ship this module itself. That would make swapping the admin site even easier.

I just tried this in a new project and it seems to work just fine.

I'm also wondering if the `otpadmin` name override on `OTPAdminSite` is still necessary?

**Comment by psagers** [comment]
This is definitely something I haven't been keeping up with, but I'd be happy to take a pull request.

Thanks,
Peter
