### ISSUE TITLE
Using BigAutoField as the Default_AUTO_FIELD causes a migration

### ISSUE THREAD

**Issue by alexgmin** [django-otp/django-otp#93]
Starting with Django 3.2 the DEFAULT_AUTO_FIELD setting is `django.db.models.BigAutoField`
https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys

On a new project using django_otp with the totp plugin causes this when running makemigrations:
```
Migrations for 'otp_totp':
  /usr/local/lib/python3.9/site-packages/django_otp/plugins/otp_totp/migrations/0003_alter_totpdevice_id.py
    - Alter field id on totpdevice
```

However, since this is not a user migration, it doesn't go into source control and other stuff.

The solution is to define the type of the Ids in the tables specifically, so for example
```
from django.db import models

class MyModel(models.Model):
    id = models.BigAutoField(primary_key=True)
```

BigAutoField is on django since 1.10, so compatibility wouldn't be an issue. The alternative to avoid a migration for something that is probably not going to be needed (Who is going to have more than 2147483647 devices, after all) would be to use `models.AutoField` instead.

**Comment by psagers** [comment]
Seems like the recommended approach is to set [AppConfig.default_auto_field](https://docs.djangoproject.com/en/3.2/ref/applications/#django.apps.AppConfig.default_auto_field) for existing third-party apps. Individual projects can create their own config classes as a workaround, but I imagine it would make sense to add default configs to the apps.
