### ISSUE TITLE
Get OTP Challenge -> select_for_update cannot be used outside of a transaction.

### ISSUE THREAD

**Issue by unformatt** [django-otp/django-otp#95]
Django 2.2.25
django-otp 1.1.3
psycopg2 2.8.6

Clicking "Get OTP Challenge" on admin login is throwing this error:

`select_for_update cannot be used outside of a transaction.`

Error is happening on this line: https://github.com/django-otp/django-otp/commit/b56f5590f455ad021bbcd4076af367d813be59b0#diff-447dcc4f960794ca1d6629f161267c8246f5655bdf1481ac80095d85467c038bR123

**Comment by psagers** [comment]
I haven't been able to reproduce this (using EmailBackend in the repo's test project). Can you get a full stack trace?

Thanks

**Comment by unformatt** [comment]
Hi @psagers - here's the [traceback](https://gist.github.com/unformatt/042a81ade95b8fa7c8c3363342f60a35). And this touches a custom `OTPAdminAuthenticationForm` which is [here](https://gist.github.com/unformatt/9b9e9a9e817ab8faf6754738c994d304).

**Comment by psagers** [comment]
Ah, that would explain it. You'll want to have a look at the latest `OTPAdminAuthenticationForm` and match its use of transactions. Or you could arrange to pass `for_verify=False` to `Device.from_persistent_id`, although that's probably more work and certainly less safe.
