### ISSUE TITLE
Import Doesn't Exist in the current version of django [Update Documentation]

### ISSUE THREAD

**Issue by DeepDiverGuy** [django-otp/django-otp#96]
HI, 

The current stable version of django is 4.0.2 and there is no callable named 'login' inside 'django.contrib.auth.views' module. 

But in your [documentation](https://django-otp-official.readthedocs.io/en/stable/auth.html): <Authentication and Authorization/ Authentication Users/ The Token Form>, the code snippet is:

```
from functools import partial
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login

@login_required
def verify(request):
   form_cls = partial(OTPTokenForm, request.user)
   return login(request, template_name='my_verify_template.html', authentication_form=form_cls)
```

The last line is unusable since there is **no "login" function available** and the third import throws an error. So, django-otp has become unusable and I am not being able to find a workaround on this core implementation. Is there any other way of using **django-otp** using the **class-based views** of the current versions of django.

**Comment by DeepDiverGuy** [comment]
**UPDATE**:

While using the authentication form directly from urls.py within LoginView.as_view(), the token is successfully delivered:

`urlpatterns = [ url(r'^accounts/login/$', LoginView.as_view(authentication_form=OTPAuthenticationForm)),]`

**Comment by DeepDiverGuy** [comment]
**UPDATE:**

The issue can be resolved just by simply specifying the token or authentication form in a LoginView: 

```
from django.contrib.auth.views import LoginView
from django_otp.forms import OTPAuthenticationForm, OTPTokenForm

class ClassName(Loginview):
    template_name = 'YourTemplatePath.html'
    authentication_form = OTPAuthenticationForm (or OTPTokenForm)
```

Then, django-otp should do the rest perfectly. But, as mentioned in the documentation, corresponding devices must be registered to corresponding users to deliver the token.

**Comment by psagers** [comment]
Yup, this documentation is out of date; thanks for the update. [django_otp.views](https://github.com/django-otp/django-otp/blob/d9095d9a57e4a1086af275c5eebdd3e1f84bb7d9/src/django_otp/views.py#L10) actually has an example of the modern equivalent. We can use that as the basis for updated documentation; feel free to send a PR if I don't get to it first.

**Comment by DeepDiverGuy** [comment]
Thanks for your response and pointing to the perfect solution!
